### PR TITLE
Update deployment docs to use JSON for CORS policy

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Status

Ready for review

## Description of Changes

Changes proposed in this pull request:

This PR updates the CORS configuration in the deployment instructions to use JSON rather than XML. When I tried setting this up myself, AWS would only accept JSON in the CORS configuration field.

## Screenshots (if appropriate)
Screenshot_2021-03-13_17-43-28

## Tests and linting

 - [x] I have rebased my changes on current `develop`

 - [ ] pytests pass in the development environment on my local machine

 - [ ] `flake8` checks pass

### CODE REVIEW

**Review by brianmwaters — APPROVED** [review]
I found this documentation page, which reads, "In the new S3 console, the CORS configuration must be JSON.": https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html, so that must be why you ran into this problem.

This is just a documentation change, and we've confirmed what's going on under the hood, so I'm just going to quickly approve and merge this myself.

Thanks for the PR!

**Comment by brianmwaters** [comment]
Wait a second, the build is failing on python 3.7... not sure what's going on with that, but it doesn't seem like your change could be the issue. We have a pending release right now for 0.6.4 (https://github.com/lucyparsons/OpenOversight/pull/859), maybe that will fix it.

**Comment by AetherUnbound** [comment]
Sounds good! Let me know if there's anything I can/need to do

**Comment by abandoned-prototype** [comment]
Thank you @AetherUnbound for not just identifying the issue, but immediately fixing our documentation too. This is greatly appreciated!
The test failing has to be some flakiness of our tests. I am re-running it now, that should be all that's needed to merge this

**Pull request merged**
