### PR TITLE
document the bulk-add-officers command

### PR DESCRIPTION
**Pull request by abandoned-prototype**
## Status

Ready for review

## Description of Changes

I wrote instructions on how to use the bulk upload feature. Feedback very welcome. I haven tested every scenario, so please either let me know or make your own edits if something turns out to be wrong.

### CODE REVIEW

**Comment by ssempervirens** [comment]
Hi @abandoned-prototype, this looks great. I am wondering if it would make sense to add this documentation to the sphinx documentation rather than this md file living at the root of OO.

**Comment by abandoned-prototype** [comment]
Thanks @ssempervirens. Is that documentation deployed anywhere? I agree that this might not be the best location for the file. It might also make sense to split the documentation in a part for organizers in new towns, basically just to tell them what data is needed and how the csv file has to look like and one part for admins of the page on how to import the file once provided by the local organizers

**Comment by redshiftzero** [comment]
nice docs! any documentation added to the `docs` directory will get deployed on merge into `develop` to: https://openoversight.readthedocs.io/en/latest/

**Comment by brianmwaters** [comment]
Note to maintainers: because we made so many changes to the bulk import code for the Vermont data, I have merged this documentation into https://github.com/brianmwaters/OpenOversight/tree/vermont, and placed it in the docs/ folder as an .rst file as requested. I will update @abandoned-prototype's documentation with any changes we've made, and will include it in my final pull request. So this PR can probably be closed.

**Comment by brianmwaters** [comment]
Closing as this has been merged into https://github.com/lucyparsons/OpenOversight/pull/703

**Pull request closed without merging**
