### PR TITLE
Complete multidepartment volunteer features

### LINKED ISSUE #321: Volunteer identification for a specific police department
Modify volunteer flow for officer identification to be for a specific police department

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

In progress

## Description of Changes

Fixes #321

Changes proposed in this pull request:

 - Makes tagger search form multi department
 - Makes officer identification multi department

## Notes for Deployment

straightforward, no db migrations

## Tests and linting
 
- [x] I have rebased my changes on current `develop`
 
- [x] pytests pass in the development environment on my local machine
 
- [x] `flake8` checks pass

### CODE REVIEW

**Comment by b-meson** [comment]
Perhaps I'm missing something but is the default search to use CPD in the test database? This is on a fresh checkout of `finish-multidepl-volunteering`. 
```
(venv) zerohistory:OpenOversight bmeson$ git branch
  develop
* finish-multidept-volunteering
 ```
screen shot 2017-12-10 at 12 04 07 pm

Other than that, this looks great! I think we are okay to merge this and fix the tests later. (famous last words).

**Comment by redshiftzero** [comment]
All tests are passing

**Comment by redshiftzero** [comment]
> Other than that, this looks great! I think we are okay to merge this and fix the tests later. (famous last words). 

Also never do this ;)

**Comment by redshiftzero** [comment]
Recall that everything was hardcoded as "Chicago Police Department". The scope of this PR was to make the volunteer workflow multi-department, which you'll see that it now is. Removing the hardcoded "Chicago Police Department" on the homepage and in "Find" is at this point trivial, but is out of scope for now. If we want to do a soft launch of Berkeley / Oakland / etc. we can open that up in a followup, but otherwise if we want to restrict searching through these departments until we've had volunteers populate the data, we should leave it hardcoded for now

**Pull request merged**
