### PR TITLE
Rename  `star_date` and `descrip`

### PR DESCRIPTION
**Pull request by michplunkett**
## Fixes issues
https://github.com/lucyparsons/OpenOversight/issues/941
https://github.com/lucyparsons/OpenOversight/issues/427

## Description of Changes
Changed the following column names:
- `star_date` -> `start_date`
- `descrip` -> `description`

## Tests and linting
 - [x] This branch is up-to-date with the `develop` branch.
 - [x] `pytest` passes on my local development environment.
 - [x] `pre-commit` passes on my local development environment.
 - [x]  Data-migration output:

```shell
$ docker exec -it openoversight-web-1 bash
$ flask db stamp head
/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2023-07-18 17:16:06,001] INFO in __init__: OpenOversight startup
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 93fc3e074dcc
$ flask db migrate -m "rename 'star_date'"
/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2023-07-18 17:17:01,906] INFO in __init__: OpenOversight startup
...
  Generating /usr/src/app/OpenOversight/migrations/versions/2023-07-18-1717_9ce70d7ebd56_rename_star_date.py ...  done
$ flask db upgrade
[2023-07-18 17:18:49,546] INFO in __init__: OpenOversight startup
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 93fc3e074dcc -> 9ce70d7ebd56, rename 'star_date'

...

(env) % make start
docker-compose build
...
[+] Running 2/2
 ✔ Container openoversight-postgres-1  Started                                                                                                                                                             0.2s 
 ✔ Container openoversight-web-1       Started                                                                                                                                                             0.3s 
(env) % docker exec -it openoversight-web-1 bash
$ flask db stamp head
/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2023-07-18 19:18:26,742] INFO in __init__: OpenOversight startup
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
$ flask db migrate -m "rename 'descrip' to 'description'"
...
INFO  [alembic.autogenerate.compare] Detected added column 'unit_types.description'
INFO  [alembic.autogenerate.compare] Detected removed index 'ix_unit_types_descrip' on 'unit_types'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_unit_types_description' on '['description']'
INFO  [alembic.autogenerate.compare] Detected removed column 'unit_types.descrip'
  Generating /usr/src/app/OpenOversight/migrations/versions/2023-07-18-1921_eb0266dc8588_rename_descrip_to_description.py ...  done
$ flask db upgrade
/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2023-07-18 19:33:12,354] INFO in __init__: OpenOversight startup
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 9ce70d7ebd56 -> eb0266dc8588, rename 'descrip' to 'description'
$
```

### CODE REVIEW

**Review by b-meson — APPROVED** [review]
I had one question in Slack (star numbers aren't the ones that rotate? star_date isn't about a rotated badge number?)

Everything else looks okay.

Freddy

**Comment by michplunkett** [comment]
Based off of this documentation from the upload sheet, it's the date they started: https://github.com/lucyparsons/OpenOversight/pull/976/files#diff-4d9694f2035e74724189f2d2e6664b3b49ef9427885aa0d109d5d2286b402c25L77-R77

**Comment by b-meson** [comment]
great, please feel free to merge.

**Comment by michplunkett** [comment]
I have it based on this PR, https://github.com/lucyparsons/OpenOversight/pull/976. If you could approve that PR then I can merge this one.

**Pull request merged**
