### PR TITLE
Release 0.3.1

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

QA in progress

## Description of Changes

- UI refresh thanks to @furfreemi's implementation of @ShawnaStewart's design 🎉 
- Enable admins to edit officer and assignment details
- Enable multi-department search in "Find an officer"

## Plan

PSA: this involves a database migration

- [x] Staging: Run database migration & deploy
- [ ] Do a bunch of the clicky clicky and check everything looks aight (dat detailed test plan amirite?)
- [ ] Merge this PR
- [ ] Prod: Run database migration & deploy

### CODE REVIEW

**Comment by redshiftzero** [comment]
Deployed to staging: https://staging.openoversight.lucyparsonslabs.com/

**Comment by b-meson** [comment]
I took a look on staging. Unfortunately, since we haven't backported the prod DB to staging, we don't have OPD / BPD officers to test against this step `Do a bunch of the clicky clicky`

**Comment by redshiftzero** [comment]
For future reference, we have CPD officers in the staging database, so you can inspect the UI changes and the Edit Officer and Edit Assignment features of this PR. I just did this and didn't hit any snags, so now I will merge and deploy to production (I just did a production backup). If other issues are found, please file. If small, I will fix them this Saturday.

**Comment by redshiftzero** [comment]
Deployed to production: https://openoversight.lucyparsonslabs.com/

**Pull request merged**
