### PR TITLE
322 homepage design revamp

### LINKED ISSUE #322: Implement design elements in homepage wireframe
Here's a slick wireframe for our homepage created by @ShawnaStewart: 

If a frontend-skilled person wants to take a stab at implementing these design elements (feel free to make smaller tickets for individual items), that would be 💯

### PR DESCRIPTION
**Pull request by furfreemi**
## Status
In progress: moves towards comp but isn't completed

## Description of Changes
Addresses #322 .

Changes proposed in this pull request:
 - Styling updates for general button look and feel
 - Formatting changes to homepage to move towards comp
 - Formatting changes to volunteer info page to move towards comp
 - Enable login on volunteer page (unsure on this one: feels weird pulling auth stuff in to main. Should all login functionality be contained in auth? If so, can easily pull out login form for now and simply link to existing login page from Volunteer section)

## Screenshots (if appropriate)
home page:
prev_home

volunteer page:
prev_volunteer

## Tests and linting
 
- [x] I have rebased my changes on current `develop`
 
- [x] pytests pass in the development environment on my local machine
 
- [x] `flake8` checks pass

### CODE REVIEW

**Comment by r4v5** [comment]
Holy cow! I'm gonna take a closer look at the changes here later and give some more specific feedback (hopefully tomorrow) but I wanted to thank you for the work you've done here already. It's a very strong start!

Re: your question in #322 ("I might have missed a strings file when I looked, but if not are you all just keeping all the text in-line for now, vs planning to translate stuff in the immediate future?") translation is important, and definitely something we want to do sooner than later for at least the home page and basic citizen flow (the volunteer flow probably can go later). That said, I won't ask that you do it as part of this work unless you want to :)

**Comment by furfreemi** [comment]
yayy sweet!! looking forward to feedback for sure :)

**Comment by furfreemi** [comment]
nice! made some updates. totally up to you as far as merging- i'll probably make some more UI changes based on all those images in the ux-docs directory, but could open another pr rather than piling more on this one :)

**Comment by b-meson** [comment]
I ran a `vagrant up` against this PR and I think it looks amazing. Thank you so much for your work! Note I didn't look at  commit af70093 but I also think its worth merging as is. We really appreciate the work @furfreemi !

**Comment by r4v5** [comment]
Thanks again for this work! By all means, please continue to iterate (though note that I actually did a squash-merge here, so you'll have Weirdness if you don't branch additional things off of current develop). I'm going to deploy this to staging so that we can see how it looks with real-world data too.

**Comment by r4v5** [comment]
https://staging.openoversight.lucyparsonslabs.com/ Annnnd it's up.

**Pull request merged**
