### PR TITLE
Profile cleanup and fixes

### LINKED ISSUE #574: Add Link button on officer profile page
Currently to add a link to an officer profile, you have to edit the whole profile and fill out the Links form at the bottom. A new user might not even know this functionality exists.

IMO it would make more sense for their to be a "New Link" button on the profile page similar to "New Note" and "New Description".

### LINKED ISSUE #610: Editing officer with blank UID results in error
Departments without unique internal identifiers shows the field as 'None' on officer profiles:
image

However, if you edit and save an officer's profile, it will save the UID as an empty string rather than NULL. This causes a problem when you edit a second officer's profile since the database will reject a second blank string unique_internal_identifier, since that field has a unique constraint:

```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_officers_unique_internal_identifier"
DETAIL:  Key (unique_internal_identifier)=() already exists.
 [SQL: 'UPDATE officers SET unique_internal_identifier=%(unique_internal_identifier)s WHERE officers.id = %(officers_id)s'] [parameters: {'unique_internal_identifier': '', 'officers_id': 219}]
```

### PR DESCRIPTION
**Pull request by dismantl**
## Status

Ready for review

## Description of Changes

Fixes #574, #610, #611, among other changes.

Changes proposed in this pull request:

 - Breadcrumb nav link didn't have quotes around href attribute
 - Officer profile pics had extra slash in URL, resulting in broken image
 - Can now edit and save officer profiles with null unique internal identifier (#610)
 - Fixed a number of inconsistencies and bugs in officer profile markup (unmatched tags, sections in wrong place, embedded video size issues, inconsistent grid classes for sections, etc.)

## Tests and linting

 - [x] I have rebased my changes on current `develop`

 - [x] pytests pass in the development environment on my local machine

 - [x] `flake8` checks pass

### CODE REVIEW

**Comment by r4v5** [comment]
Can you add a test that updates two officers and would reproduce #610 if we regress? This is a change in invariants that we hadn’t previously hit so I’d like to make sure we don’t accidentally break it again.

**Comment by dismantl** [comment]
Yup, can do! The tests don't really do anything with officer uids yet so I will make sure that happens.

**Comment by dismantl** [comment]
@r4v5 ok made some corrections. The new test `edit_officers_with_blank_uids` covers #610. When that test is run on the `develop` branch, it will raise a unique constraint violation exception.

I also made fixes to a number of other tests in that module that didn't correctly check error/success conditions.

**Comment by sibrahi5** [comment]
Reviewing, had one question about test_data file changes. LGTM otherwise.

**Comment by r4v5** [comment]
There are two merge conflicts (OpenOversight/tests/conftest.py, OpenOversight/tests/routes/test_officer_and_department.py); would you be able to rebase this and then we can merge it?

**Pull request merged**
