### PR TITLE
[Cleaner] Classify cops quickly with hotkeys :-D

### PR DESCRIPTION
**Pull request by elimisteve**
## Status

Ready for review

## Description of Changes

Implemented change recommended by @redshiftzero at https://github.com/lucyparsons/OpenOversight/pull/267

Changes proposed in this pull request:

 - Underline first letter of No/Skip/Yes buttons to signal hotkeys

## Tests and linting
 
 [x] I have rebased my changes on current `develop`
 
 [x] pytests pass in the development environment on my local machine
 
 [x] `flake8` checks pass

### CODE REVIEW

**Comment by jujueyeball** [comment]
I want to review and merge this but I have a dumb question which is how do I look at it? I haven't put everything locally yet (I'm taking a git class right now!) and idk how to look. ty, patient friends

**Comment by jujueyeball** [comment]
i will figure it out

**Comment by elimisteve** [comment]
@jujueyeball Clone https://github.com/elimisteve/OpenOversight then `git checkout hotkeys-classify-cop-cleaner`

**Comment by jujueyeball** [comment]
Foiled for now sry

**Comment by elimisteve** [comment]
@redshiftzero How's this look?

**Comment by elimisteve** [comment]
@redshiftzero :+1: Sweet :-).

Please deploy to production soon so I (and others) can use this feature!

**Pull request merged**
