### PR TITLE
Explain that we will provide tips / $$$ for contributions

### PR DESCRIPTION
**Pull request by redshiftzero**
I decided to keep this simple and just have the amount be S, M, L for simplicity since everything marked tip is marked that way because it's an important issue to implement.

### CODE REVIEW

**Comment by redshiftzero** [comment]
@magpiewings let me know what you think

**Comment by b-meson** [comment]
I think this one is ready for merge.

**Comment by redshiftzero** [comment]
@magpiewings ping

**Comment by magpiewings** [comment]
sorry for delay - 👍🏼 from me

**Pull request merged**
