### PR TITLE
Address Coveralls bug

### LINKED ISSUE #1099: Address issue with coverage file not uploading
## What issue are you seeing?
It's somehow linked to this PR, https://github.com/lucyparsons/OpenOversight/pull/1082, but I'll hunt it down later.

Failed job: https://github.com/lucyparsons/OpenOversight/actions/runs/8952227770/job/24589381732

### PR DESCRIPTION
**Pull request by michplunkett**
## Fixes issue
https://github.com/lucyparsons/OpenOversight/issues/1099

## Description of Changes
Fixing the Coveralls upload bug.

## Tests and Linting
 - [x] This branch is up-to-date with the `develop` branch.
 - [x] `pytest` passes on my local development environment.
 - [x] `pre-commit` passes on my local development environment.

Screenshot 2024-06-03 at 4 51 04 PM

### CODE REVIEW

**Comment by michplunkett** [comment]
Could you take a look at this build, @sea-kelp, and tell me if anything looks obviously wrong: https://github.com/lucyparsons/OpenOversight/actions/runs/9335574698/job/25695125327?pr=1100

It's linked to this PR: https://github.com/lucyparsons/OpenOversight/pull/1082

I'm also seeing that the branches have not been updated on here since April 17th: https://coveralls.io/github/lucyparsons/OpenOversight

**Comment by sea-kelp** [comment]
@michplunkett fixed - I think what happened is that the coverage file was being created by docker when setting up the [bind mount](https://github.com/lucyparsons/OpenOversight/blob/716d6d4278de9e49355ec4b958984b07c79a3d43/docker-compose.yml#L70), which gave it weird permissions.

I haven't dug into the linked PR so not sure why that change in particular broke this workflow

Can you check that the coverage has been uploaded successfully?

**Comment by michplunkett** [comment]
I'll take a look! I tried doing that from the Docker side, but it didn't seem to work: https://github.com/lucyparsons/OpenOversight/pull/1100/commits/f19fc87cfb2ea447a64358bc82e98d58001c6109

Good find, @sea-kelp! I'll check it out.

**Comment by michplunkett** [comment]
Looks good to me! 

Screenshot 2024-06-03 at 4 06 02 PM

https://coveralls.io/builds/67861750

**Comment by sea-kelp** [comment]
> I'll take a look! I tried doing that from the Docker side, but it didn't seem to work: [f19fc87](https://github.com/lucyparsons/OpenOversight/commit/f19fc87cfb2ea447a64358bc82e98d58001c6109)
> 
> Good find, @sea-kelp! I'll check it out.

The file is mounted from the host machine onto the container filesystem, so the file would need to be created on the host side
https://docs.docker.com/storage/bind-mounts/

**Review by sea-kelp — APPROVED** [review]

**Pull request merged**
