### PR TITLE
Release 0.5.1

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Work in progress

## Description of Changes

Deploy latest changes:
- Add bulk officer upload
- Update About page text
- Switch from Flask-Script to Flask CLI
- Log who submitted a photo if they are logged in
- Improve user management
- Improve officer profiles

## Notes for Deployment

- [x] Deployed to staging
- [ ] Testing / QA - help very welcome on finding issues
- [ ] Deployed to production

### CODE REVIEW

**Comment by r4v5** [comment]
This has now been deployed to staging.

**Comment by r4v5** [comment]
I also updated staging to run in a python3 venv, and ran through the following flows:
- [x] unauthenticated and authenticated officer search
- [x] unauthenticated image submission
- [x] logging in (administrator)
- [x] reviewing images for officers
- [x] tagging images
That all seems to work.

Can you think of anything else to run through for this particular PR or shall we call it good, @redshiftzero ? If the latter, I can do the cutover/merge tonight.

**Comment by r4v5** [comment]
@McEileen did some additional testing, which reminds me we should also add this to the manual pre-release QA process:
- [x] new user signup/email
I see the signup email in the sending account's outbox, so this is fine for now. Considering this :+1: to :shipit:

**Comment by redshiftzero** [comment]
thanks for getting this over the finish line @r4v5

**Pull request merged**
