### PR TITLE
Show police department on the image and tag detail pages

### LINKED ISSUE #305: Add department ID to image pages
We should show what department an image is associated with on the `image/` page

Related: #205

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

Ready for review

## Description of Changes

Fixes #305.

Changes proposed in this pull request:

 - Adds foreign key constraint (and migration) between images and departments tables
 - Shows the police department on the image page:

screen shot 2017-09-21 at 10 05 51 pm

## Tests and linting
 
- [x] I have rebased my changes on current `develop`
 
- [x] pytests pass in the development environment on my local machine
 
- [x] `flake8` checks pass

### CODE REVIEW

**Comment by r4v5** [comment]
Ah: for the first one, there's a manage.py task added in #310 (https://github.com/lucyparsons/OpenOversight/pull/310/commits/f6862488e88b6e5cd4605a94d0a693f8d3fd90ba) to address it, which I think probably should be pulled into this branch, since it's technically part of this change ('image-related things'). And the image upload route is part of the previous changeset. Okay cool.

**Comment by r4v5** [comment]
words

**Comment by redshiftzero** [comment]
You probably figured this out hence the merge, but writing out here for posterity: 

> doesn't the raw_images.department_id column need to be populated (presumably with '1' for the first department for existing images) in order to not violate the constraint you'll be imposing on it?

Yep!  The `manage.py link_images_to_department` command was added in #303 to handle this (a bit hacky maybe, but :woman_shrugging:). I added a similar command in #310 for doing the same thing with two other tables that should store `department_id` (in prep for adding a foriegn key constraint later on).

**Comment by redshiftzero** [comment]
Ohh I see ya moved that bit o' code over here. That's :100:

**Pull request merged**
