### PR TITLE
Bulk upload officers

### LINKED ISSUE #247: Management command to add officer rosters
So as people try to spin up OpenOversight in their own city, or as we want to update our own roster, we want some way of adding officers in bulk from files we get through FOIA. We have implemented issue #214 and have yet to be implemented issue #213 as stopgaps, but we would like to be able to do this in bulk.

### PR DESCRIPTION
**Pull request by dismantl**
## Status

Ready for review

## Description of Changes

Fixes #247.

Changes proposed in this pull request:

 - Change badge_exists to officer_exists to match on full name
 - Added unique constraint to officer table based on full name, since that's how the `officer_exists` function checks for duplicates.
 - Adding officer suffix field to database migration

## Notes for Deployment

I tested using the following csv:
```
department_id,badge,last_name,suffix,first_name,middle_initial,race,gender,employment_date,birth_year,rank
1,129022,butts,jr.,seymour,e,black,female,01-01-2001,2000,POLICE OFFICER
```

Output from populating a fresh db w/ test data, then using the bulk uploader:
```sh
$ python ../create_db.py 
$ python ../test_data.py -p
[*] Populating database with test data...
[*] Completed successfully!
$ python manage.py bulk_add_officers ../test.csv 
created 1 officers
$ python manage.py bulk_add_officers ../test.csv 
Skipping creation of existing officer seymour butts for department id 1
created 0 officers

```

## Tests and linting

 - [x] I have rebased my changes on current `develop`

 - [x] pytests pass in the development environment on my local machine

 - [x] `flake8` checks pass

### CODE REVIEW

**Comment by dismantl** [comment]
> It is not impossible that there are several cops with the same name especially in big departments.

Are we sure this is true? Just seems unlikely to me. This would mean the officers have the same first, middle, last, and suffix. I'd rather not check against badge numbers because, as in Chicago and Baltimore, badge numbers are recycled (and sometimes not even tracked properly or at all). In my opinion, it would be good to allow uploading rosters of officers even when badge numbers aren't available.

Long term, I think it would make more sense to use generalized unique IDs for officers to check for duplicates (#462) rather than names or badge numbers. I would also suspect those identifiers are easier to get in most places, since they are usually used by a department's or city's HR. That's true for Baltimore at least, but I'd be curious to hear about other cities.

**Comment by abandoned-prototype** [comment]
I think we have to assume that we don't have access to a middle name (or middle initial) in some cities. I am specifically thinking of NYC, and #510. The data we have there only has first and last names. And of the 1840 entries, there are eight with same name, but different "tax-numbers" which is uniquely assigned to an officer.

But I definitely agree that it would be good to have some unique ID, maybe it would possible to generate that one depending on the department

**Comment by redshiftzero** [comment]
Beautiful, thanks for taking this over @dismantl.

> Are we sure this is true? Just seems unlikely to me. This would mean the officers have the same first, middle, last, and suffix.

Bad news... due to common names like Rodriguez, we already have this situation with CPD:

https://openoversight.com/officer/21111
https://openoversight.com/officer/21112

And we know from comrades in NYPD that this is also the case there (they have 40k+ officers so that makes sense). so we can't add this unique constraint in the database

> In my opinion, it would be good to allow uploading rosters of officers even when badge numbers aren't available.

agreed 100%

> I think we have to assume that we don't have access to a middle name (or middle initial) in some cities.

also agreed 100%

For Chicago, we weren't able to get the internal unique IDs (organizations like the [Invisible Institute](https://invisible.institute/) have tried and failed to get them, I believe the argument by law enforcement was that they are "private" records and not subject to FOIA). For departments where we are able to get them, totally agreed this is the best approach.

**Comment by dismantl** [comment]
Yeah yall are totally right about the name uniqueness issue. So would the duplicate check function return true if all three of badge number, first name, and last name match? And once #462 is completed the function can also check against unique identifiers when they are available.

**Comment by redshiftzero** [comment]
> all three of badge number, first name, and last name match

Ah yep, this should be sufficient

**Comment by dismantl** [comment]
Ok I added updates:

- Updated officer duplicate checking to use first name, last name, badge number
- Added more fields and checks to the CSV import command
- Removed unique constraint from previous commit

Ready for review again.

**Comment by redshiftzero** [comment]
fantastic work! do you have bandwidth to add tests to this one?

**Comment by dismantl** [comment]
Yup I can work on that!

**Comment by dismantl** [comment]
Coming back to this now. One thing I'd like to add to the `officer_exists` function is to check against a unique identifier if that is available in the data, otherwise fall back to using name/badge.

I'd also like this feature to support updating an existing database of officers, not just replacing what's there. That way we can hang on to extra added info such as notes, descriptions, incidents, etc.

**Comment by sibrahi5** [comment]
Flask?

**Comment by dismantl** [comment]
@sibrahi5 Yeah I planned to use Flask CLI commands for it, so I rebased the this branch onto the `flask-cli` branch from PR #556, and have been working off of that. Here's what it looks like so far: https://github.com/lucyparsons/OpenOversight/compare/develop...openjusticebaltimore:247-bulk-upload-officers#diff-fa538f187486df65f41ca0d7d8d17c92R94

**Comment by dismantl** [comment]
Ok I added several tests and fixes, so this is ready for review again.

**Comment by sibrahi5** [comment]
LGTM. :O

**Pull request merged**
