### PR TITLE
Release 0.3.3

### PR DESCRIPTION
**Pull request by redshiftzero**
## Status

in progress

## Description of Changes

* Adds area coordinator
* Bugfixes

## Notes for Deployment

- [x] Staging backup
- [x] Database migration, redeploy to staging
- [x] QA
- [x] Prod backup
- [ ] Database migration, redeploy to production

### CODE REVIEW

**Comment by redshiftzero** [comment]
The latest is deployed to https://staging.openoversight.lucyparsonslabs.com/

I nominate @magpiewings and @b-meson and others to poke around - if you make accounts and tell me your usernames I can add ye as area coordinators. If all looks good then this will go to prod (likely on Wednesday if not before)

**Comment by b-meson** [comment]
@redshiftzero my username is `freddy@lucyparsonslabs.com`. Saving a default profile did not work. Steps to reproduce: login to the staging. set a default department to "Berkley". Navigate to "find an officer", you'll notice "Chicago Police" is the default.

**Comment by redshiftzero** [comment]
Ah... well that's actually expected, the default department is only used for the submit functionality (see: #420). Maybe I'll work on that ticket today prior to sending all this to prod... 🤔

**Comment by redshiftzero** [comment]
Ehhh... okay I started working on this over in #420, but in the interest of incremental progress I'm going to deploy current `develop`

**Comment by redshiftzero** [comment]
Database migration done, this is deployed to production, no issues

**Pull request merged**
