### PR TITLE
Generate test data

### LINKED ISSUE #57: Set up Travis and Coveralls
Set up travis and coveralls to run our tests. needs to be done once we make the repo public so we can get that free service

### PR DESCRIPTION
**Pull request by scuerda**
OK, lots going on here. I have test coverage up around 85% but there are a few tests that are inexplicably breaking.

`test_find_form_submission` and `test_bad_form` both fail to correctly redirect. This leads me to believe that while some other tests are passing, they shouldn't be.  Oddly `test_tagger_lookup` and `test_tagger_gallery_bad_form` have the same form as the two failing tests and yet they pass. I'm pretty stumped as to why this is happening as I've used the exact same test pattern previously and it's worked fine.

The application now implements a factory pattern, which makes for easier use of different configurations in testing, development, production, etc.

Coveralls is set up and will work once integrated via travis and travis build should just work.

I have yet to fully test pagination. If I can't figure out a way around these strange test failures, I'll add some `WebTest` functional tests. We should be able to use `WebTest` for most of the form-based testing in lieu of full fledged selenium testing.

This should fully close #57 and gets pretty close to address #108

### CODE REVIEW

**Comment by redshiftzero** [comment]
Hey @scuerda this is looking really great! Thanks for these contributions 😺. One note before I make any inline comments: let's do two things to [make the git history a bit nicer](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html): 

- can I get you to do a bit of squashing to e.g. squash the "more blah" commits into one? It looks you were mostly working out the CI setup in there, so one commit with "Adds Travis configuration" might be good.
- can you rebase this on develop? This will remove the merge commits

**Comment by scuerda** [comment]
@redshiftzero Yep, I can do that. Might not get to it until tomorrow AM.

**Comment by r4v5** [comment]
I took a swing at rebasing this on current develop (which was... painful, shall we say? with a bunch of merge conflicts that I may have resolved incorrectly), and ended up with https://github.com/lucyparsons/OpenOversight/tree/generate-test-data which fails with https://travis-ci.org/lucyparsons/OpenOversight/builds/177865528.

**Comment by scuerda** [comment]
@r4v5 I took another pass at rebasing and I *think* I got things figured out. I am not particularly facile with rebasing, but I think I managed to keep the history fairly intact. I disabled the failing tests for now, but left them in. The "failures" might be in terms of the test fixture setup and not in terms of functionality. As I mentioned above, it might be easier to handle what is trying to be accomplished in those tests with `WebTest`

**Comment by redshiftzero** [comment]
OK I cherry picked all your commits here into PR #126 (rebase ended up being thorny and I wanted to fix the vagrant dev VM before merging in to master). Thanks @scuerda !

**Pull request closed without merging**
